# Coingecko supported currencies
# Aparently, even tho Coingecko return those, many of them are actually not compatible

fiat = {
    "usd": "United States Dollar",
    "aed": "United Arab Emirates Dirham",
    "ars": "Argentine Peso",
    "aud": "Australian Dollar",
    "bdt": "Bangladeshi Taka",
    "bhd": "Bahraini Dinar",
    "bmd": "Bermudian Dollar",
    "brl": "Brazilian Real",
    "cad": "Canadian Dollar",
    "chf": "Swiss Franc",
    "clp": "Chilean Peso",
    "cny": "Chinese Yuan",
    "czk": "Czech Koruna",
    "dkk": "Danish Krone",
    "eur": "Euro",
    "gbp": "British Pound Sterling",
    "gel": "Georgian Lari",
    "hkd": "Hong Kong Dollar",
    "huf": "Hungarian Forint",
    "idr": "Indonesian Rupiah",
    "ils": "Israeli New Shekel",
    "inr": "Indian Rupee",
    "jpy": "Japanese Yen",
    "krw": "South Korean Won",
    "kwd": "Kuwaiti Dinar",
    "lkr": "Sri Lankan Rupee",
    "mmk": "Myanmar Kyat",
    "mxn": "Mexican Peso",
    "myr": "Malaysian Ringgit",
    "ngn": "Nigerian Naira",
    "nok": "Norwegian Krone",
    "nzd": "New Zealand Dollar",
    "php": "Philippine Peso",
    "pkr": "Pakistani Rupee",
    "pln": "Polish Zloty",
    "rub": "Russian Ruble",
    "sar": "Saudi Riyal",
    "sek": "Swedish Krona",
    "sgd": "Singapore Dollar",
    "thb": "Thai Baht",
    "try": "Turkish Lira",
    "twd": "New Taiwan Dollar",
    "uah": "Ukrainian Hryvnia",
    "vef": "Venezuelan Bolívar",
    "vnd": "Vietnamese Dong",
    "zar": "South African Rand"
}
